# https://dev.to/mojemoron/how-to-connect-your-django-app-to-a-dockerized-postgresql-and-pgadmin-133o

services:

  db:
    restart: always
    image: postgres
    container_name: demo-postgres 
    environment:
      - POSTGRES_USER=demouser
      - POSTGRES_PASSWORD=demopassword
      - POSTGRES_DB=demo_database
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  # Probably redundant but whatever
  pgadmin:
      image: dpage/pgadmin4
      container_name: demo-pgadmin 
      depends_on:
        - db
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: root
      restart: always


volumes:
  postgres_data: